/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PacoteA;

import java.util.ArrayList;

/**
 *
 * @author ygor
 */
public class DeckDialog extends javax.swing.JDialog {

    private static ArrayList<Deck> deckList = new ArrayList();
    
    /**
     * Creates new form DeckDialog
     */
    public DeckDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pesquisarJB.doClick();
        decksComboB.setModel(new javax.swing.DefaultComboBoxModel<>(((String[]) DeckDialog.getDeckNomes().toArray())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decksComboB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        deckJList = new javax.swing.JList<>();
        addJB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoPesquisaJList = new javax.swing.JList<>();
        removeJB = new javax.swing.JButton();
        pesquisaJTF = new javax.swing.JTextField();
        pesquisarJB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        deletarDeckJB = new javax.swing.JButton();
        criarDeckJB = new javax.swing.JButton();
        criarDeckJTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        decksComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        decksComboB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decksComboBActionPerformed(evt);
            }
        });

        deckJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        deckJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(deckJList);

        addJB.setText("add");
        addJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJBActionPerformed(evt);
            }
        });

        resultadoPesquisaJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        resultadoPesquisaJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(resultadoPesquisaJList);

        removeJB.setText("remove");

        pesquisarJB.setText("pesquisar");
        pesquisarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarJBActionPerformed(evt);
            }
        });

        jLabel2.setText("Deck");

        deletarDeckJB.setText("deletar deck");
        deletarDeckJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarDeckJBActionPerformed(evt);
            }
        });

        criarDeckJB.setText("criar deck");
        criarDeckJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarDeckJBActionPerformed(evt);
            }
        });

        jLabel3.setText("cards");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(criarDeckJB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(criarDeckJTF)
                .addGap(88, 88, 88)
                .addComponent(decksComboB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletarDeckJB)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeJB)
                            .addComponent(addJB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pesquisarJB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisaJTF)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decksComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletarDeckJB)
                    .addComponent(criarDeckJB)
                    .addComponent(criarDeckJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(addJB)
                        .addGap(36, 36, 36)
                        .addComponent(removeJB)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJBActionPerformed
        // TODO add your handling code here:
        String cardName = resultadoPesquisaJList.getSelectedValue();
        
        
        
        
        
    }//GEN-LAST:event_addJBActionPerformed

    private void pesquisarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarJBActionPerformed
        // TODO add your handling code here:
        ArrayList<String> listaPesquisa = Gerenciamento2.pesquisarNomeDeCarta(Gerenciamento2.getCartas(), pesquisaJTF.getText());
        resultadoPesquisaJList.setListData(((String[]) listaPesquisa.toArray()));
    }//GEN-LAST:event_pesquisarJBActionPerformed

    private void deletarDeckJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarDeckJBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarDeckJBActionPerformed

    private void criarDeckJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarDeckJBActionPerformed
        // TODO add your handling code here:
        String novoDeck = ((String) decksComboB.getSelectedItem());
        
        
        
        
        
    }//GEN-LAST:event_criarDeckJBActionPerformed

    private void decksComboBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decksComboBActionPerformed
        // TODO add your handling code here:
        int index = decksComboB.getSelectedIndex();
        //deckList.get(index).getCards();
        deckJList.setListData(deckList.get(index).getCards());
        
        
        
        //decksComboB.set
        
    }//GEN-LAST:event_decksComboBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeckDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeckDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeckDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeckDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeckDialog dialog = new DeckDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public static ArrayList<String> getDeckNomes(){
        ArrayList<String> listaNomes = new ArrayList();
        for(Deck c: deckList){
            listaNomes.add(c.getNome());
        }
        
        return listaNomes;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJB;
    private javax.swing.JButton criarDeckJB;
    private javax.swing.JTextField criarDeckJTF;
    private javax.swing.JList<String> deckJList;
    private javax.swing.JComboBox<String> decksComboB;
    private javax.swing.JButton deletarDeckJB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pesquisaJTF;
    private javax.swing.JButton pesquisarJB;
    private javax.swing.JButton removeJB;
    private javax.swing.JList<String> resultadoPesquisaJList;
    // End of variables declaration//GEN-END:variables
}
