package PacoteA;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ygor
 * @param modal 
 * @param l   lista com os nomes das cartas 
 * @param cartasPraEscolher quantidade de cartas que serão escolhidas
 * Cria um JDialog que ajuda na escolha de nomes de cartas e retorna o resultado 
 * no método retornarEscolha(int n);
 */
public class EscolherCarta extends javax.swing.JDialog {

    /**
     * Creates new form EscolherCarta
     */
    public EscolherCarta(java.awt.Frame parent, boolean modal, ArrayList<String> l, int cartasPraEscolher) {
        super(parent, modal);
        this.cartasPraEscolher = cartasPraEscolher;
        
        initComponents();
        
        arrayL1 = new ArrayList();
        for(String s: l){
            arrayL1.add(s);
        }
        atualizarJList(arrayL1);        
    }
    
    public EscolherCarta(java.awt.Frame parent, boolean modal, ArrayList<String> l, int cartasPraEscolher, String dica) {
        super(parent, modal);
        this.cartasPraEscolher = cartasPraEscolher;
        
        initComponents();
        
        jLabel1.setText(dica);
        arrayL1 = new ArrayList();
        for(String s: l){
            arrayL1.add(s);
        }
        atualizarJList(arrayL1);        
    }
    
    
    public void atualizarJList(ArrayList<String> aList){
        String[] l = new String[aList.size()];
        for(int i = 0; i < l.length; i++){
            l[i] = aList.get(i);
        }   
        jList1.setListData(l);
    }
    
    
    /**
     * 
     * @param n quantidade de elementos selecionados
     * @return listaIndices - um vetor contendo os Indices selecionados no JDialog
     */
    private int[] retornarEscolha(int n){     
        int[] listaIndices = jList1.getSelectedIndices();   
        System.out.println("listaIndices: " + listaIndices.length);
        if(listaIndices.length == n){
            return listaIndices;
        }else{
            JOptionPane.showMessageDialog(null, "Selecionou a quantidade errada de cartas", "erro", JOptionPane.WARNING_MESSAGE);            
        }
        return null;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        OkJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Escolha");

        jLabel1.setText("Escolha ....");

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        OkJB.setText("Ok");
        OkJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(OkJB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(OkJB)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkJBActionPerformed
        // TODO add your handling code here:
        int[] lista = retornarEscolha(cartasPraEscolher);
        
        if((lista != null && lista.length == cartasPraEscolher)){
            setVisible(false);
            dispose();
            this.resultado = lista;
        }else{
            this.resultado = new int[1];
        }
        
        
    }//GEN-LAST:event_OkJBActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        DueloVisao.colorirSelecao(jList1);
    }//GEN-LAST:event_jList1ValueChanged

    public ArrayList<String> getArrayL1() {
        return arrayL1;
    }

    /**
     * @param args the command line arguments
     */
    public void setArrayL1(ArrayList<String> arrayL1) {
        this.arrayL1 = arrayL1;
    }

    
    /*
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        ArrayList<String> teste = new ArrayList<String>(List.of("teste1", "teste2", "teste3"));
        int qCard = 2;

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EscolherCarta dialog = new EscolherCarta(new javax.swing.JFrame(), true, teste, qCard);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
    }
    */
    
    private ArrayList<String> arrayL1;
    private int cartasPraEscolher;
    private int[] resultado;
    
    public int[] getResultado(){
        return this.resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkJB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
