/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PacoteA;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ygor
 */
public class PedraPapelTesoura extends javax.swing.JDialog {
    
    private boolean resultado;
    /**
     * Creates new form PedraPapelTesoura
     */
    public PedraPapelTesoura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputJCB = new javax.swing.JComboBox<>();
        okJB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jogadaOP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        inputJCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pedra", "papel", "tesoura" }));

        okJB.setText("OK");
        okJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJBActionPerformed(evt);
            }
        });

        jLabel1.setText("VS");

        jogadaOP.setBackground(new java.awt.Color(255, 51, 51));
        jogadaOP.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(okJB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(inputJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(jogadaOP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jogadaOP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(okJB)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJBActionPerformed
        // TODO add your handling code here:
        int selecionado = inputJCB.getSelectedIndex();
        //0 = pedra; 1 = papel; 2 = tesoura;
        Random random = new Random();
        boolean escolha = true;
        int op = random.nextInt(3);
        //op = 0;
        
        boolean done = false;
        
        if(op == 0){
            jogadaOP.setText("pedra");
        }else if(op == 1){
            jogadaOP.setText("papel");
        }else if(op == 2){
            jogadaOP.setText("tesoura");
        }


        if(selecionado == op){
            JOptionPane.showMessageDialog(null, "Empate");
        }else if((selecionado == 0 && op == 2)||(selecionado == 1 && op == 0)||(selecionado == 2 && op == 1)){
            //jogador1 ganha
            JOptionPane.showMessageDialog(null, "Jogador1 ganhou");
            int n = JOptionPane.showConfirmDialog(null, "deseja comecar o duelo?");
            if(n == 0){
                escolha = true;
            }else if(n == 1){
                escolha = false;
            }else{
                escolha = random.nextBoolean();
            }
            done = true;
            setVisible(false);
            dispose(); 

        }else{
            //jogador2 ganha
            JOptionPane.showMessageDialog(null, "Jogador2 ganhou");
            escolha = random.nextBoolean();
            
            done = true;
            setVisible(false);
            dispose();
        }
        
        if(done){
            System.out.println(escolha);
            resultado = escolha;
        }
        
        //return escolha;
    }//GEN-LAST:event_okJBActionPerformed
    
    /*
      @param args the command line arguments
     
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PedraPapelTesoura dialog = new PedraPapelTesoura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    */

    public boolean isResultado() {
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> inputJCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jogadaOP;
    private javax.swing.JButton okJB;
    // End of variables declaration//GEN-END:variables
}
